### ISSUE TITLE
Create games page (your turn, their turn, history of games)

### ISSUE THREAD

**Issue by Joeaculberson** [Joeaculberson/VideoGameTrivia#3]

**Comment by jade-we** [comment]
We can edit the games/index/html/erb filefor this purpose. We also need to sort the games accordingly and pass them to the correct forms.

My idea for this is to  
1. get a list of games that contain the player's email in either user email or opponents email 
2. split that into two more lists based on whether or not the user turn email equals that user's email 
3. send the two lists to your turn and their turn forms, respectively

I'm not certain how to do finished games. If we're storing pieces so that a finished game will be denoted by one of the player's having their piece string be "1 2 3 4 5 6" then me might have to check that neither player's piece string equals that when getting/splitting the initial lists and then grab a seperate list in which the player's email equals the user email or opponent email and one of the player's piece string equals "1 2 3 4 5 6".

Another way to do it would be that when a game is finished the currentplayer email is set to "none". That way, when we grab the initial list of games we can split it into three lists: player's email equals useremail, doesn't equal useremail or "done", and equals "done" and forward them to the your turn, their turn, and finished forms respectively.
